language: csharp
mono: none
dotnet: 1.0.4
dist: trusty
sudo: false
install:
  - dotnet restore ./src/BCLExtensions.sln
script:
  - dotnet build ./src/BCLExtensions.sln
  - dotnet test ./src/BCLExtensions.Tests/BCLExtensions.Tests.csproj
cache:
  directories:
  - ./BuildPackages