language: csharp
solution: ./src/BCLExtensions.sln
install:
  - nuget restore ./src/BCLExtensions.sln
  - chmod +x ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe
script:
  - xbuild /p:Configuration=Release ./src/BCLExtensions.sln
  - mono ./src/packages/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/BCLExtensions.Tests/bin/Release/BCLExtensions.Tests.dll
