version: 1.0.0.{build}
os: Windows Server 2012 R2
environment:
  COVERALLS_REPO_TOKEN:
    secure: BBCvZzwY+hZfJFv/nnoi708GIAELA2a3gN2+D6xE14vejYrxjpWyAfhK4Kj0HSSy
  COVERITY_TOKEN:
    secure: ZbRwfjyUYFFxQEIjHf5kwFYzOWcw51aA0DRztbcM3OY=
  COVERITY_EMAIL:
    secure: YNNLrvdTPJBtXcWskGnutoOOXbWeulhguf0c7iX9Gis=
  CODECOV_TOKEN:
    secure: D9LlnEw1hjjZ320aASvHsFokCoiEMUEUp4d1M0Q+eufflb39A+TR80w+reBjGP0h
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: BCLExtensionsCoverage.xml
  name: BCLExtensionsCoverage.xml
- path: BCLExtensions.*.zip
- path: BCLExtensions.*.nupkg
- provider: GitHub
  release: $($env:GitVersion_SemVer)
  auth_token:
    secure: hH6A9i7v+sf5mZy9FLQVG7n4UpLWkUhpshIsia7sGi1ONr+iMKroqjkJk0Hsi3nK
  artifact: /.*\.nupkg/
  prerelease: true
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  api_key:
    secure: 4XLKYHbHXYJuc9SCTYZt5VzxE/XDBpjWSttRIK3ZGux5TwIgAnhMBamo16fjVmzS
  on:
    branch: /release-.*/
    APPVEYOR_REPO_TAG: true
