version: 1.0.0.{build}
os: Windows Server 2012 R2
branches:
  except:
  - master
environment:
  COVERALLS_REPO_TOKEN:
    secure: BBCvZzwY+hZfJFv/nnoi708GIAELA2a3gN2+D6xE14vejYrxjpWyAfhK4Kj0HSSy
install:
- ps: .\build.environment.ps1
- ps: psake .\build.tasks.ps1 appveyor-install
build_script:
- ps: psake .\build.tasks.ps1 appveyor-build
test_script:
- ps: psake .\build.tasks.ps1 appveyor-test
artifacts:
- path: BCLExtensionsCoverage.xml
  name: BCLExtensionsCoverage.xml
- path: BCLExtensions.*.zip
- path: BCLExtensions.*.nupkg